//+------------------------------------------------------------------+
//|                                        MACD_REV_Sequential.mq5   |
//|                                      Generated by Antigravity    |
//+------------------------------------------------------------------+
#property copyright "Antigravity"
#property link      ""
#property version   "1.20"
#property indicator_chart_window
#property indicator_buffers 9
#property indicator_plots   2

//--- plot Buy
#property indicator_label1  "Buy"
#property indicator_type1   DRAW_ARROW
#property indicator_color1  clrLime
#property indicator_style1  STYLE_SOLID
#property indicator_width1  2
//--- plot Sell
#property indicator_label2  "Sell"
#property indicator_type2   DRAW_ARROW
#property indicator_color2  clrRed
#property indicator_style2  STYLE_SOLID
#property indicator_width2  2

//--- Inputs
input int    InpSweepLookback      = 23;       // Sweep Lookback Period
input int    InpChopPeriod         = 14;       // Choppiness Index Period
input double InpChopThresh         = 64.85;    // Choppiness Threshold
input int    InpMacdFast           = 12;       // MACD Fast Period (EMA)
input int    InpMacdSlow           = 26;       // MACD Slow Period (EMA)
input int    InpMacdSignal         = 9;        // MACD Signal Period (EMA)
input int    InpAtrPeriod          = 14;       // ATR Period for SL/TP
input double InpSlAtrMult          = 2.2;      // Stop Loss ATR Multiplier
input double InpTpAtrMult          = 1.5;      // Take Profit ATR Multiplier
input int    InpSeqLookback        = 6;        // Sequential Trigger Window (bars)

//--- Buffers
double BuyBuffer[];
double SellBuffer[];
double ema_fast[];
double ema_slow[];
double macd_line[];
double macd_signal[];
double sweep_low_arr[];
double sweep_high_arr[];
double chop_arr[];

//--- Indicator Handles
int atr_handle;

//+------------------------------------------------------------------+
//| Custom indicator initialization function                         |
//+------------------------------------------------------------------+
int OnInit()
  {
   //--- indicator buffers mapping
   SetIndexBuffer(0, BuyBuffer, INDICATOR_DATA);
   SetIndexBuffer(1, SellBuffer, INDICATOR_DATA);
   SetIndexBuffer(2, ema_fast, INDICATOR_CALCULATIONS);
   SetIndexBuffer(3, ema_slow, INDICATOR_CALCULATIONS);
   SetIndexBuffer(4, macd_line, INDICATOR_CALCULATIONS);
   SetIndexBuffer(5, macd_signal, INDICATOR_CALCULATIONS);
   SetIndexBuffer(6, sweep_low_arr, INDICATOR_CALCULATIONS);
   SetIndexBuffer(7, sweep_high_arr, INDICATOR_CALCULATIONS);
   SetIndexBuffer(8, chop_arr, INDICATOR_CALCULATIONS);
   
   PlotIndexSetInteger(0, PLOT_ARROW, 233); // Up arrow
   PlotIndexSetInteger(1, PLOT_ARROW, 234); // Down arrow
   
   ArraySetAsSeries(BuyBuffer, false);
   ArraySetAsSeries(SellBuffer, false);
   ArraySetAsSeries(ema_fast, false);
   ArraySetAsSeries(ema_slow, false);
   ArraySetAsSeries(macd_line, false);
   ArraySetAsSeries(macd_signal, false);
   ArraySetAsSeries(sweep_low_arr, false);
   ArraySetAsSeries(sweep_high_arr, false);
   ArraySetAsSeries(chop_arr, false);
     
   atr_handle = iATR(_Symbol, _Period, InpAtrPeriod);
   if(atr_handle == INVALID_HANDLE)
     {
      Print("Failed to get ATR handle");
      return(INIT_FAILED);
     }

   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Calculate True Range                                             |
//+------------------------------------------------------------------+
double TrueRange(int i, const double &high[], const double &low[], const double &close[])
  {
   if(i == 0) return high[0] - low[0];
   double hl = high[i] - low[i];
   double hc = MathAbs(high[i] - close[i-1]);
   double lc = MathAbs(low[i] - close[i-1]);
   return MathMax(hl, MathMax(hc, lc));
  }

//+------------------------------------------------------------------+
//| Draw SL/TP Lines                                                 |
//+------------------------------------------------------------------+
void DrawLevels(datetime time, double price, double sl, double tp, bool is_long)
  {
   string prefix = is_long ? "Long_" : "Short_";
   string sl_name = prefix + "SL_" + TimeToString(time);
   string tp_name = prefix + "TP_" + TimeToString(time);
   
   ObjectCreate(0, sl_name, OBJ_TREND, 0, time, sl, time + PeriodSeconds()*10, sl);
   ObjectSetInteger(0, sl_name, OBJPROP_COLOR, clrRed);
   ObjectSetInteger(0, sl_name, OBJPROP_STYLE, STYLE_DASH);
   ObjectSetInteger(0, sl_name, OBJPROP_RAY_RIGHT, true);
   
   ObjectCreate(0, tp_name, OBJ_TREND, 0, time, tp, time + PeriodSeconds()*10, tp);
   ObjectSetInteger(0, tp_name, OBJPROP_COLOR, clrGreen);
   ObjectSetInteger(0, tp_name, OBJPROP_STYLE, STYLE_DASH);
   ObjectSetInteger(0, tp_name, OBJPROP_RAY_RIGHT, true);
  }

//+------------------------------------------------------------------+
//| Custom indicator iteration function                              |
//+------------------------------------------------------------------+
int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
  {
   if(rates_total < MathMax(InpSweepLookback, InpChopPeriod) + 2) return 0;
   
   int start = prev_calculated;
   if(start == 0)
     {
      start = MathMax(InpSweepLookback, InpChopPeriod) + 1;
      ArrayInitialize(BuyBuffer, 0.0);
      ArrayInitialize(SellBuffer, 0.0);
      ArrayInitialize(sweep_low_arr, 0.0);
      ArrayInitialize(sweep_high_arr, 0.0);
      ArrayInitialize(chop_arr, 0.0);
     }
     
   double atr[];
   ArraySetAsSeries(atr, false);
   if(CopyBuffer(atr_handle, 0, 0, rates_total, atr) <= 0) return 0;
   
   double alpha_fast = 2.0 / (InpMacdFast + 1.0);
   double alpha_slow = 2.0 / (InpMacdSlow + 1.0);
   double alpha_sig = 2.0 / (InpMacdSignal + 1.0);
   
   for(int i = start; i < rates_total; i++)
     {
      BuyBuffer[i] = 0.0;
      SellBuffer[i] = 0.0;
      sweep_low_arr[i] = 0.0;
      sweep_high_arr[i] = 0.0;
      chop_arr[i] = 0.0;
      
      // 1. Calculate MACD strictly matching Python (EMA based)
      double price = close[i];
      if(i == 1) // Provide initial seeding
        {
         ema_fast[i-1] = close[i-1];
         ema_slow[i-1] = close[i-1];
         macd_line[i-1] = 0.0;
         macd_signal[i-1] = 0.0;
        }
        
      ema_fast[i] = (price - ema_fast[i-1]) * alpha_fast + ema_fast[i-1];
      ema_slow[i] = (price - ema_slow[i-1]) * alpha_slow + ema_slow[i-1];
      macd_line[i] = ema_fast[i] - ema_slow[i];
      macd_signal[i] = (macd_line[i] - macd_signal[i-1]) * alpha_sig + macd_signal[i-1];
      
      double macd_hist_current = macd_line[i] - macd_signal[i];
      double macd_hist_prev = macd_line[i-1] - macd_signal[i-1];
      
      bool macd_up = macd_hist_current > macd_hist_prev;
      bool macd_down = macd_hist_current < macd_hist_prev;
      
      // 2. Calculate Sweep Logic
      double swing_high = -1.0;
      double swing_low = 99999999.0;
      
      for(int j = i - InpSweepLookback; j < i; j++)
        {
         if(high[j] > swing_high) swing_high = high[j];
         if(low[j] < swing_low) swing_low = low[j];
        }
        
      bool sweep_low_cond = (low[i] < swing_low) && (close[i] > swing_low);
      bool sweep_high_cond = (high[i] > swing_high) && (close[i] < swing_high);
      
      if(sweep_low_cond) sweep_low_arr[i] = 1.0;
      if(sweep_high_cond) sweep_high_arr[i] = 1.0;
      
      // 3. Calculate Choppiness Index
      double sum_tr = 0;
      double chop_hh = -1.0;
      double chop_ll = 99999999.0;
      
      for(int j = i - InpChopPeriod + 1; j <= i; j++)
        {
         sum_tr += TrueRange(j, high, low, close);
         if(high[j] > chop_hh) chop_hh = high[j];
         if(low[j] < chop_ll) chop_ll = low[j];
        }
        
      double chop = 0;
      if(chop_hh - chop_ll > 0 && InpChopPeriod > 0)
        {
         chop = 100 * (MathLog10(sum_tr / (chop_hh - chop_ll)) / MathLog10(InpChopPeriod));
        }
        
      bool is_chop = chop > InpChopThresh;
      if(is_chop) chop_arr[i] = 1.0;
      
      // 4. Sequential Evaluator (Triggering ONE AFTER THE OTHER)
      // The final trigger is the MACD tick. 
      // We look back 'InpSeqLookback' bars for the preceding Sweep and Chop.
      
      if (macd_up)
        {
         bool found_sweep = false;
         bool found_chop = false;
         
         // Scan the previous N bars (excluding current bar to ensure sequentiality)
         for(int j = i - 1; j >= MathMax(0, i - InpSeqLookback); j--)
           {
            if(sweep_low_arr[j] == 1.0) found_sweep = true;
            if(chop_arr[j] == 1.0) found_chop = true;
           }
           
         if(found_sweep && found_chop)
           {
            BuyBuffer[i] = low[i] - atr[i] * 0.5; // Draw arrow below
            
            // Only draw objects on the latest bar or real-time to avoid cluttering historical chart
            if(i >= rates_total - 2)
              {
               double sl = close[i] - (atr[i] * InpSlAtrMult);
               double tp = close[i] + (atr[i] * InpTpAtrMult);
               DrawLevels(time[i], close[i], sl, tp, true);
              }
           }
        }
        
      if (macd_down)
        {
         bool found_sweep = false;
         bool found_chop = false;
         
         // Scan the previous N bars (excluding current bar to ensure sequentiality)
         for(int j = i - 1; j >= MathMax(0, i - InpSeqLookback); j--)
           {
            if(sweep_high_arr[j] == 1.0) found_sweep = true;
            if(chop_arr[j] == 1.0) found_chop = true;
           }
           
         if(found_sweep && found_chop)
           {
            SellBuffer[i] = high[i] + atr[i] * 0.5; // Draw arrow above
            
            // Only draw objects on the latest bar or real-time to avoid cluttering historical chart
            if(i >= rates_total - 2)
              {
               double sl = close[i] + (atr[i] * InpSlAtrMult);
               double tp = close[i] - (atr[i] * InpTpAtrMult);
               DrawLevels(time[i], close[i], sl, tp, false);
              }
           }
        }
     }
     
   return(rates_total);
  }
//+------------------------------------------------------------------+
